model = "gpt-5.2"
review_model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
approval_policy = "on-request"
sandbox_mode = "read-only"
network_access = true
notifications = false
hide_agent_reasoning = true
show_raw_agent_reasoning = false
windows_wsl_setup_acknowledged = false
web_search_request = true
personality = "pragmatic"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2" = "gpt-5.2-codex"
